language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-pykickstart
  - sudo apt-get install -y python-enchant
install:
  - "pip install -r requirements.txt"
script:
  - "ksvalidator build_tools/kickstarts/centos-7-adb-vagrant.ks"
  - "python src/spellcheck.py ."
notifications:
 email: false

