language: python
python:
  - "2.7"
before_install:
  - apt-get install -y python-pykickstart
  - apt-get install -y python-enchant
script:
  - "ksvalidator build_tools/kickstarts/centos-7-adb-vagrant.ks"
  - "python src/spellcheck.py ."
notifications:
 email: false

